version: "3.9"
services:
  app:
    build: .
    restart: always
    environment:
      DB_STRING: "postgresql+asyncpg://postgres:postgres@db/XOGame"
      AUTH_SECRET: "jDQn5yVD9vQrZpfDm4CNgPAr"
    links:
      - db
  db:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
  nginx:
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: hi@dvlkv.ru
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d/:ro
      - letsencrypt:/etc/letsencrypt
    links:
      - app


volumes:
  pg_data: {}
  letsencrypt: {}