swagger: "2.0"
openapi: 3.0.0
info:
  description: |
    API Description
  version: "1.0"
  title: API Title
  contact:
    name: my@contact.com
basePath: /api/v1/
schemes:
  - http
  - https

components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
# 2) Apply the security globally to all operations
security:
  - bearerAuth: []         # use the same name as above

paths:
  /account:
    get:
      description: Gets current user if authorized
      tags:
        - Account
      produces:
        - application/json
      responses:
        "200":
          description: Successful operation. Return user json object
        "401":
          description: Unauthorized access error. Returns error object
        "500":
          description: Unexpected server error. Returns error object
    post:
      description: Creates user
      tags:
        - Account
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User object
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
              name:
                type: string
      responses:
        "200":
          description: Successful operation. Return user json object
        "401":
          description: Unauthorized access error. Returns error object
        "409":
          description: User already exists error. Returns error object
        "500":
          description: Unexpected server error. Returns error object
