openapi: 3.0.0
info:
  description: |
    Simple XO Game
  version: "1.0"
  title: XO Game API
  contact:
    name: Danila Volkov
    email: hi@dvlkv.ru
    url: https://github.com/mrmld
servers:
  - url: /api/v1/

components:
  securitySchemes:
    BearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []

paths:
  /account:
    description: Methods for managing user account
    get:
      description: Gets current user if authorized
      tags:
        - Account
      responses:
        "200":
          description: Successful operation. Return user json object
        "401":
          description: Unauthorized access error. Returns error object
        "500":
          description: Unexpected server error. Returns error object
    post:
      description: Creates user
      tags:
        - Account
      requestBody:
        description: User object
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
      responses:
        "200":
          description: Successful operation. Return user json object
        "401":
          description: Unauthorized access error. Returns error object
        "409":
          description: User already exists error. Returns error object
        "500":
          description: Unexpected server error. Returns error object

  /auth:
    post:
      security: []
      description: Authorizes user
      tags:
        - Auth
      requestBody:
        description: Auth data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Successful operation. Return jwt token object
        "401":
          description: Unauthorized access error. Returns error object
        "500":
          description: Unexpected server error. Returns error object

  /games:
    get:
      description: Get user games
      tags:
        - Game
      responses:
        "200":
          description: Successful operation. Returns history of user games
    post:
      description: Start a new game
      tags:
        - Game
      requestBody:
        description: Game object
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                height:
                  type: integer
                width:
                  type: integer
      responses:
        "200":
          description: Successful operation. Returns game object

  "/games/{id}":
    get:
      description: Gets game by specified id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      tags:
        - Game
      responses:
        "200":
          description: Successful operation. Returns game object

    post:
      description: Make a move
      tags:
        - Game
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Move object
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                x:
                  type: integer
                y:
                  type: integer
                seq:
                  type: integer
      responses:
        "200":
          description: Successful operation. Returns game object and next computer's move
        "400":
          description: "Invalid parameters. Returns error object with current game"
        "500":
          description: Unexpected server error. Returns error object


